modLoader="javafml"
loaderVersion="[38,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Max-Health-Fix/issues"
license="LGPL v2.1"

[[mods]]
modId="maxhealthfix"
updateJSONURL="https://updates.blamejared.com/get?n=maxhealthfix&gv=1.18"
version="${file.jarVersion}"
displayName="${modName}"
displayURL="${modHomepage}"
credits="${modCredits}"
authors="${modAuthor}"
description='''
${modDescription}
'''
itemIcon="minecraft:golden_apple"