modLoader = "javafml"
license = "LGPL 2.1"
issueTrackerURL = "https://github.com/Darkhax-Minecraft/Max-Health-Fix/issues"

[[mods]]
modId = "maxhealthfix"
version = "26.1.2.0"
displayName = "MaxHealthFix"
updateJSONURL = "https://updates.blamejared.com/get?n=maxhealthfix&gv=26.1.2&ml=neoforge"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/max-health-fix"
logoFile = "logo_maxhealthfix.png"
logoBlur = false
credits = "This project is made possible with Patreon support from players like you. Thank you! lothrazar, techsquirrel, Keyana , Darkosto, Tobias Ward, noobanidus"
authors = "Darkhax"
description = "Fixes the infamous MC-17876 bug. This bug would cause players with above 20 health to be reset when the restart the game."

[[mixins]]
config = "maxhealthfix.common.mixins.json"

[[mixins]]
config = "maxhealthfix.neoforge.mixins.json"

[[dependencies.maxhealthfix]]
modId = "minecraft"
type = "required"
versionRange = "26.1"
ordering = "NONE"
side = "BOTH"

[[dependencies.maxhealthfix]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.0.1-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.maxhealthfix]]
modId = "prickle"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

